version: "3"

services:
  api:
    build: .
    #image: strapi/strapi
    environment:
      - APP_NAME=svartviken-cms
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=db
      - DATABASE_PORT=27017
      - DATABASE_NAME=svartviken
      - DATABASE_USERNAME=
      - DATABASE_PASSWORD=
      - DATABASE_SSL=false
      - DATABASE_AUTHENTICATION_DATABASE=strapi
      - HOST=localhost
    ports:
      - 1337:1337
    volumes:
      - ./svartviken-cms:/usr/src/api/svartviken-cms
      #- /usr/src/api/strapi-app/node_modules
    depends_on:
      - db
    restart: always

  db:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=svartviken
    ports:
      - 27017:27017
    volumes:
      - /mathmoose/dockerVolMongo/db:/data/db
    restart: always
